### ISSUE TITLE
import _c error

### ISSUE THREAD

**Issue by HansolHyewon** [zhangxiaosong18/FreeAnchor#27]
Traceback (most recent call last):
  File "tools/multi_scale_test.py", line 7, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "/home/hansol/PycharmProjects/FreeAnchor/maskrcnn_benchmark/engine/inference.py", line 20, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/home/hansol/PycharmProjects/FreeAnchor/maskrcnn_benchmark/structures/boxlist_ops.py", line 6, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "/home/hansol/PycharmProjects/FreeAnchor/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .nms import nms
  File "/home/hansol/PycharmProjects/FreeAnchor/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /home/hansol/PycharmProjects/FreeAnchor/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv
Traceback (most recent call last):
  File "/home/hansol/anaconda3/envs/free/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hansol/anaconda3/envs/free/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hansol/anaconda3/envs/free/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/hansol/anaconda3/envs/free/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/hansol/anaconda3/envs/free/bin/python', '-u', 'tools/multi_scale_test.py', '--local_rank=0', '--config-file', 'config/free_anchor_X-101-FPN_e2x.yaml', 'MODEL.WEIGHT', 'free_anchor_X-64x4d-101-FPN_e2x.pth', 'DATASETS.TEST', 'coco_2017_val']' returned non-zero exit status 1.

I followed the install.me course but there are the above errors.
How can we solve this?

**Comment by HansolHyewon** [comment]
I solved it.

**Comment by HansolHyewon** [comment]
I solved this problem.
